# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: donacionesOfrecidas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'donacionesOfrecidas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64onacionesOfrecidas.proto\x12\x13\x64onacionesOfrecidas\"\x07\n\x05\x45mpty\"}\n\x1b\x44onacionesOfrecidasResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0f\x65xternal_org_id\x18\x02 \x01(\t\x12\x11\n\toferta_id\x18\x03 \x01(\t\x12\x11\n\tcontenido\x18\x04 \x01(\t\x12\x13\n\x0brecibida_en\x18\x05 \x01(\t\"j\n!ListarDonacionesOfrecidasResponse\x12\x45\n\x0bsolicitudes\x18\x01 \x03(\x0b\x32\x30.donacionesOfrecidas.DonacionesOfrecidasResponse2\x8d\x01\n\x1a\x44onacionesOfrecidasService\x12o\n\x19listarSolicitudesVigentes\x12\x1a.donacionesOfrecidas.Empty\x1a\x36.donacionesOfrecidas.ListarDonacionesOfrecidasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'donacionesOfrecidas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=50
  _globals['_EMPTY']._serialized_end=57
  _globals['_DONACIONESOFRECIDASRESPONSE']._serialized_start=59
  _globals['_DONACIONESOFRECIDASRESPONSE']._serialized_end=184
  _globals['_LISTARDONACIONESOFRECIDASRESPONSE']._serialized_start=186
  _globals['_LISTARDONACIONESOFRECIDASRESPONSE']._serialized_end=292
  _globals['_DONACIONESOFRECIDASSERVICE']._serialized_start=295
  _globals['_DONACIONESOFRECIDASSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
