# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


from . import eventos_pb2 as eventos__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eventos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearEvento = channel.unary_unary(
                '/eventos.EventoService/CrearEvento',
                request_serializer=eventos__pb2.CrearEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.CrearEventoResponse.FromString,
                _registered_method=True)
        self.ModificarEvento = channel.unary_unary(
                '/eventos.EventoService/ModificarEvento',
                request_serializer=eventos__pb2.ModificarEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.ModificarEventoResponse.FromString,
                _registered_method=True)
        self.BajaEvento = channel.unary_unary(
                '/eventos.EventoService/BajaEvento',
                request_serializer=eventos__pb2.BajaEventoRequest.SerializeToString,
                response_deserializer=eventos__pb2.BajaEventoResponse.FromString,
                _registered_method=True)
        self.AsignarOQuitarMiembro = channel.unary_unary(
                '/eventos.EventoService/AsignarOQuitarMiembro',
                request_serializer=eventos__pb2.AsignarQuitarRequest.SerializeToString,
                response_deserializer=eventos__pb2.AsignarQuitarResponse.FromString,
                _registered_method=True)
        self.ListarEventosDisponibles = channel.unary_unary(
                '/eventos.EventoService/ListarEventosDisponibles',
                request_serializer=eventos__pb2.Empty.SerializeToString,
                response_deserializer=eventos__pb2.ListarEventosResponse.FromString,
                _registered_method=True)


class EventoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsignarOQuitarMiembro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarEventosDisponibles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearEvento,
                    request_deserializer=eventos__pb2.CrearEventoRequest.FromString,
                    response_serializer=eventos__pb2.CrearEventoResponse.SerializeToString,
            ),
            'ModificarEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarEvento,
                    request_deserializer=eventos__pb2.ModificarEventoRequest.FromString,
                    response_serializer=eventos__pb2.ModificarEventoResponse.SerializeToString,
            ),
            'BajaEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaEvento,
                    request_deserializer=eventos__pb2.BajaEventoRequest.FromString,
                    response_serializer=eventos__pb2.BajaEventoResponse.SerializeToString,
            ),
            'AsignarOQuitarMiembro': grpc.unary_unary_rpc_method_handler(
                    servicer.AsignarOQuitarMiembro,
                    request_deserializer=eventos__pb2.AsignarQuitarRequest.FromString,
                    response_serializer=eventos__pb2.AsignarQuitarResponse.SerializeToString,
            ),
            'ListarEventosDisponibles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarEventosDisponibles,
                    request_deserializer=eventos__pb2.Empty.FromString,
                    response_serializer=eventos__pb2.ListarEventosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventos.EventoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventos.EventoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventoService/CrearEvento',
            eventos__pb2.CrearEventoRequest.SerializeToString,
            eventos__pb2.CrearEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventoService/ModificarEvento',
            eventos__pb2.ModificarEventoRequest.SerializeToString,
            eventos__pb2.ModificarEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventoService/BajaEvento',
            eventos__pb2.BajaEventoRequest.SerializeToString,
            eventos__pb2.BajaEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsignarOQuitarMiembro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventoService/AsignarOQuitarMiembro',
            eventos__pb2.AsignarQuitarRequest.SerializeToString,
            eventos__pb2.AsignarQuitarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarEventosDisponibles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventos.EventoService/ListarEventosDisponibles',
            eventos__pb2.Empty.SerializeToString,
            eventos__pb2.ListarEventosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
