# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarInventario = channel.unary_unary(
                '/inventario.InventarioService/RegistrarInventario',
                request_serializer=inventario__pb2.InventarioRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioResponse.FromString,
                _registered_method=True)
        self.ModificarInventario = channel.unary_unary(
                '/inventario.InventarioService/ModificarInventario',
                request_serializer=inventario__pb2.ModificarInventarioRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioResponse.FromString,
                _registered_method=True)
        self.BajaInventario = channel.unary_unary(
                '/inventario.InventarioService/BajaInventario',
                request_serializer=inventario__pb2.BajaInventarioRequest.SerializeToString,
                response_deserializer=inventario__pb2.InventarioResponse.FromString,
                _registered_method=True)
        self.ListarInventario = channel.unary_unary(
                '/inventario.InventarioService/ListarInventario',
                request_serializer=inventario__pb2.Empty.SerializeToString,
                response_deserializer=inventario__pb2.ListarInventarioResponse.FromString,
                _registered_method=True)
        self.ObtenerInventarioPorId = channel.unary_unary(
                '/inventario.InventarioService/ObtenerInventarioPorId',
                request_serializer=inventario__pb2.ObtenerInventarioPorIdRequest.SerializeToString,
                response_deserializer=inventario__pb2.ObtenerInventarioPorIdResponse.FromString,
                _registered_method=True)


class InventarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarInventario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarInventario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaInventario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarInventario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerInventarioPorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarInventario,
                    request_deserializer=inventario__pb2.InventarioRequest.FromString,
                    response_serializer=inventario__pb2.InventarioResponse.SerializeToString,
            ),
            'ModificarInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarInventario,
                    request_deserializer=inventario__pb2.ModificarInventarioRequest.FromString,
                    response_serializer=inventario__pb2.InventarioResponse.SerializeToString,
            ),
            'BajaInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaInventario,
                    request_deserializer=inventario__pb2.BajaInventarioRequest.FromString,
                    response_serializer=inventario__pb2.InventarioResponse.SerializeToString,
            ),
            'ListarInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarInventario,
                    request_deserializer=inventario__pb2.Empty.FromString,
                    response_serializer=inventario__pb2.ListarInventarioResponse.SerializeToString,
            ),
            'ObtenerInventarioPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerInventarioPorId,
                    request_deserializer=inventario__pb2.ObtenerInventarioPorIdRequest.FromString,
                    response_serializer=inventario__pb2.ObtenerInventarioPorIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventario.InventarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventario.InventarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/RegistrarInventario',
            inventario__pb2.InventarioRequest.SerializeToString,
            inventario__pb2.InventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ModificarInventario',
            inventario__pb2.ModificarInventarioRequest.SerializeToString,
            inventario__pb2.InventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BajaInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/BajaInventario',
            inventario__pb2.BajaInventarioRequest.SerializeToString,
            inventario__pb2.InventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ListarInventario',
            inventario__pb2.Empty.SerializeToString,
            inventario__pb2.ListarInventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerInventarioPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ObtenerInventarioPorId',
            inventario__pb2.ObtenerInventarioPorIdRequest.SerializeToString,
            inventario__pb2.ObtenerInventarioPorIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
