# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventario.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\x12\ninventario\"c\n\x11InventarioRequest\x12\x11\n\tcategoria\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x14\n\x0cusuario_alta\x18\x04 \x01(\t\"m\n\x1aModificarInventarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x1c\n\x14usuario_modificacion\x18\x04 \x01(\t\"A\n\x15\x42\x61jaInventarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x14usuario_modificacion\x18\x02 \x01(\t\"B\n\x12InventarioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x32\x9d\x02\n\x11InventarioService\x12T\n\x13RegistrarInventario\x12\x1d.inventario.InventarioRequest\x1a\x1e.inventario.InventarioResponse\x12]\n\x13ModificarInventario\x12&.inventario.ModificarInventarioRequest\x1a\x1e.inventario.InventarioResponse\x12S\n\x0e\x42\x61jaInventario\x12!.inventario.BajaInventarioRequest\x1a\x1e.inventario.InventarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTARIOREQUEST']._serialized_start=32
  _globals['_INVENTARIOREQUEST']._serialized_end=131
  _globals['_MODIFICARINVENTARIOREQUEST']._serialized_start=133
  _globals['_MODIFICARINVENTARIOREQUEST']._serialized_end=242
  _globals['_BAJAINVENTARIOREQUEST']._serialized_start=244
  _globals['_BAJAINVENTARIOREQUEST']._serialized_end=309
  _globals['_INVENTARIORESPONSE']._serialized_start=311
  _globals['_INVENTARIORESPONSE']._serialized_end=377
  _globals['_INVENTARIOSERVICE']._serialized_start=380
  _globals['_INVENTARIOSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
