# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import solicitudesExternas_pb2 as solicitudesExternas__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in solicitudesExternas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolicitudesExternasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listarSolicitudesVigentes = channel.unary_unary(
                '/solicitudesExternas.SolicitudesExternasService/listarSolicitudesVigentes',
                request_serializer=solicitudesExternas__pb2.Empty.SerializeToString,
                response_deserializer=solicitudesExternas__pb2.ListarSolicitudesExternasResponse.FromString,
                _registered_method=True)


class SolicitudesExternasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listarSolicitudesVigentes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolicitudesExternasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listarSolicitudesVigentes': grpc.unary_unary_rpc_method_handler(
                    servicer.listarSolicitudesVigentes,
                    request_deserializer=solicitudesExternas__pb2.Empty.FromString,
                    response_serializer=solicitudesExternas__pb2.ListarSolicitudesExternasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'solicitudesExternas.SolicitudesExternasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('solicitudesExternas.SolicitudesExternasService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolicitudesExternasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listarSolicitudesVigentes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/solicitudesExternas.SolicitudesExternasService/listarSolicitudesVigentes',
            solicitudesExternas__pb2.Empty.SerializeToString,
            solicitudesExternas__pb2.ListarSolicitudesExternasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
